- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: æœªåˆ†ç±»'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: ç±»åˆ«ï¼šæœªåˆ†ç±»
- en: 'date: 2024-05-29 13:23:52'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: æ—¥æœŸï¼š2024å¹´05æœˆ29æ—¥ 13:23:52
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'ğŸ§ Genie: Generative Interactive Environments'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: ğŸ§ ç²¾çµï¼šç”Ÿæˆäº¤äº’ç¯å¢ƒ
- en: æ¥æºï¼š[https://sites.google.com/view/genie-2024](https://sites.google.com/view/genie-2024)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: æ¥æºï¼š[https://sites.google.com/view/genie-2024](https://sites.google.com/view/genie-2024)
- en: Jake Bruce*, Michael Dennis*, Ashley Edwards*, Jack Parker-Holder*, Yuge (Jimmy)
    Shi*, Edward Hughes, Matthew Lai, Aditi Mavalankar, Richie Steigerwald, Chris
    Apps, Yusuf Aytar, Sarah Bechtle, Feryal Behbahani, Stephanie Chan, Nicolas Heess,
    Lucy Gonzalez, Simon Osindero, Sherjil Ozair, Scott Reed, Jingwei Zhang, Konrad
    Zolna, Jeff Clune, Nando de Freitas, Satinder Singh, Tim RocktÃ¤schel*
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: Jake Bruce*ï¼ŒMichael Dennis*ï¼ŒAshley Edwards*ï¼ŒJack Parker-Holder*ï¼Œå²å®‡æ ¼ï¼ˆJimmyï¼‰*ï¼Œçˆ±å¾·åÂ·ä¼‘æ–¯ï¼Œé©¬ä¿®Â·è±ï¼Œé˜¿è¿ªæÂ·é©¬ç“¦å…°å¡å°”ï¼Œé‡Œå¥‡Â·æ–¯æ³°æ ¼æ²ƒå°”å¾·ï¼Œå…‹é‡Œæ–¯Â·é˜¿æ™®æ–¯ï¼Œå°¤ç´ å¤«Â·è‰¾å¡”å°”ï¼Œèæ‹‰Â·è´å¥‡å°”ï¼Œè´¹é‡Œäºšå°”Â·è´å“ˆå·´å°¼ï¼Œæ–¯è’‚èŠ¬å¦®Â·é™ˆï¼Œå°¼å¤æ‹‰æ–¯Â·å¸Œæ–¯ï¼Œéœ²è¥¿Â·å†ˆè¨é›·æ–¯ï¼Œè¥¿è’™Â·å¥¥è¾›å¾·ç½—ï¼Œè°¢å°”å‰å°”Â·å¥¥æ³½å°”ï¼Œæ–¯ç§‘ç‰¹Â·é‡Œå¾·ï¼Œå¼ é–å¨ï¼Œåº·æ‹‰å¾·Â·ä½å°”çº³ï¼Œæ°å¤«Â·å…‹å¢æ©ï¼Œå—å¤šÂ·å¾·å¼—é›·å¡”æ–¯ï¼Œè¨å»·å¾·å°”Â·è¾›æ ¼ï¼Œè’‚å§†Â·ç½—å…‹å¡”èˆå°”*
- en: '*Equal contribution'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '*ç­‰åŒè´¡çŒ®'
- en: Please contact Ashley Edwards ([edwardsashley@google.com](mailto:edwardsashley@google.com)),
    Jack Parker-Holder ([jparkerholder@google.com](mailto:jparkerholder@google.com))
    or Jake Bruce ([jacobbruce@google.com](mailto:jacobbruce@google.com)) for additional
    questions :)
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: å¦‚æœ‰ä»»ä½•ç–‘é—®ï¼Œè¯·è”ç³» Ashley Edwards ([edwardsashley@google.com](mailto:edwardsashley@google.com))ï¼ŒJack
    Parker-Holder ([jparkerholder@google.com](mailto:jparkerholder@google.com)) æˆ–
    Jake Bruce ([jacobbruce@google.com](mailto:jacobbruce@google.com)) :)
