- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: æœªåˆ†ç±»'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: æœªåˆ†ç±»'
- en: 'date: 2024-05-27 14:47:56'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-27 14:47:56'
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Built-in workaround for applications hiding under the MacBook Pro notch
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: å†…ç½®è§£å†³æ–¹æ¡ˆï¼Œè§£å†³ MacBook Pro å‡¹æ§½ä¸‹éšè—çš„åº”ç”¨ç¨‹åºé—®é¢˜
- en: æ¥æºï¼š[https://flaky.build/built-in-workaround-for-applications-hiding-under-the-macbook-pro-notch](https://flaky.build/built-in-workaround-for-applications-hiding-under-the-macbook-pro-notch)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: æ¥æºï¼š[https://flaky.build/built-in-workaround-for-applications-hiding-under-the-macbook-pro-notch](https://flaky.build/built-in-workaround-for-applications-hiding-under-the-macbook-pro-notch)
- en: ğŸ’¡
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: ğŸ’¡
- en: '**TL;DR:** You can adjust MacOS whitespace settings from the command line to
    display more application icons in the top right section of the menu bar.'
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '**TL;DRï¼š** æ‚¨å¯ä»¥é€šè¿‡å‘½ä»¤è¡Œè°ƒæ•´ MacOS çš„ç©ºç™½è®¾ç½®ï¼Œä»¥åœ¨èœå•æ å³ä¸Šæ–¹æ˜¾ç¤ºæ›´å¤šåº”ç”¨ç¨‹åºå›¾æ ‡ã€‚'
- en: '[](#cbd74db3d6d549f4a966ee049c6616e3 "Hidden Apps Beneath the 14â€ and 16â€ MacBook
    Pro Notch")Hidden Apps Beneath the 14â€ and 16â€ MacBook Pro Notch'
  id: totrans-8
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: '[](#cbd74db3d6d549f4a966ee049c6616e3 "14â€ å’Œ 16â€ MacBook Pro å‡¹æ§½ä¸‹éšè—çš„åº”ç”¨ç¨‹åº")14â€
    å’Œ 16â€ MacBook Pro å‡¹æ§½ä¸‹éšè—çš„åº”ç”¨ç¨‹åº'
- en: A frustrating aspect of the new MacBook Pro models is the notch. The notch itself
    isn't the problem; rather, it's that Apple hasn't automatically adjusted the menu
    bar icons so they don't hide behind the notch when many apps are running.
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: æ–° MacBook Pro æ¨¡å‹çš„ä»¤äººæ²®ä¸§çš„ä¸€é¢æ˜¯å‡¹æ§½ã€‚å‡¹æ§½æœ¬èº«å¹¶ä¸æ˜¯é—®é¢˜æ‰€åœ¨ï¼›ç›¸åï¼Œé—®é¢˜åœ¨äºè‹¹æœæ²¡æœ‰è‡ªåŠ¨è°ƒæ•´èœå•æ å›¾æ ‡ï¼Œä»¥ä¾¿åœ¨è¿è¡Œè®¸å¤šåº”ç”¨ç¨‹åºæ—¶å®ƒä»¬ä¸ä¼šéšè—åœ¨å‡¹æ§½åé¢ã€‚
- en: My colleagues often suggest purchasing
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: æˆ‘çš„åŒäº‹ç»å¸¸å»ºè®®è´­ä¹°
- en: '[Bartender](https://www.macbartender.com/)'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: '[Bartender](https://www.macbartender.com/)'
- en: for about 20â‚¬ to solve this issue. While it offers many features, I've refused
    to pay for a 3rd party solution to Apple's poor design decision. I have nothing
    against Bartender but I just donâ€™t want to install yet another app into my machine
    to solve such a simple problem.
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: å¤§çº¦ 20 æ¬§å…ƒæ¥è§£å†³è¿™ä¸ªé—®é¢˜ã€‚è™½ç„¶å®ƒæä¾›äº†è®¸å¤šåŠŸèƒ½ï¼Œä½†æˆ‘æ‹’ç»ä¸ºè‹¹æœçš„ç³Ÿç³•è®¾è®¡å†³ç­–æ”¯ä»˜ç¬¬ä¸‰æ–¹è§£å†³æ–¹æ¡ˆã€‚æˆ‘å¯¹ Bartender æ²¡æœ‰ä»»ä½•æ„è§ï¼Œä½†æˆ‘åªæ˜¯ä¸æƒ³åœ¨æˆ‘çš„æœºå™¨ä¸Šå®‰è£…å¦ä¸€ä¸ªåº”ç”¨ç¨‹åºæ¥è§£å†³è¿™æ ·ä¸€ä¸ªç®€å•çš„é—®é¢˜ã€‚
- en: 'Recently, I discovered a free, built-in macOS workaround that doesn''t require
    installing Bartender or any other additional apps. See the results in the images
    below:'
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: æœ€è¿‘ï¼Œæˆ‘å‘ç°äº†ä¸€ä¸ªå…è´¹çš„ï¼Œå†…ç½®çš„ macOS è§£å†³æ–¹æ¡ˆï¼Œä¸éœ€è¦å®‰è£… Bartender æˆ–ä»»ä½•å…¶ä»–é¢å¤–çš„åº”ç”¨ç¨‹åºã€‚è¯·å‚è§ä¸‹é¢çš„å›¾åƒä¸­çš„ç»“æœï¼š
- en: '[](#00131674fa014ca6a177465547292c21 "Adjusting the Menu Bar Whitespace Settings
    from the Command Line")Adjusting the Menu Bar Whitespace Settings from the Command
    Line'
  id: totrans-14
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
  zh: '[](#00131674fa014ca6a177465547292c21 "é€šè¿‡å‘½ä»¤è¡Œè°ƒæ•´èœå•æ ç©ºç™½è®¾ç½®")é€šè¿‡å‘½ä»¤è¡Œè°ƒæ•´èœå•æ ç©ºç™½è®¾ç½®'
- en: 'You can modify the default padding and spacing in the Menu bar by opening **Terminal.app**
    and executing the following commands:'
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: æ‚¨å¯ä»¥é€šè¿‡æ‰“å¼€ **Terminal.app** å¹¶æ‰§è¡Œä»¥ä¸‹å‘½ä»¤æ¥ä¿®æ”¹èœå•æ çš„é»˜è®¤å¡«å……å’Œé—´è·ï¼š
- en: '[PRE0]'
  id: totrans-16
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: You can adjust the values from `0` to `6` to accommodate even more icons. Personally,
    I found `6` to be a good fit. This will allow you to add more items to your menu
    bar before they will be hidden under the notch. I estimate that with the value
    of `6` I can fit 21 apps to the menu bar with my 14â€ MBP. If your apps will again
    be hidden under the notch you can just lower this value.
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: ä½ å¯ä»¥å°†å€¼ä»`0`è°ƒæ•´åˆ°`6`ä»¥é€‚åº”æ›´å¤šçš„å›¾æ ‡ã€‚å°±æˆ‘ä¸ªäººè€Œè¨€ï¼Œæˆ‘å‘ç°`6`æ˜¯ä¸€ä¸ªä¸é”™çš„é€‰æ‹©ã€‚è¿™å°†å…è®¸æ‚¨åœ¨èœå•æ ä¸­æ·»åŠ æ›´å¤šé¡¹ç›®ï¼Œè€Œå®ƒä»¬ä¸ä¼šè¢«éšè—åœ¨å‡¹æ§½ä¸‹ã€‚æˆ‘ä¼°è®¡ä½¿ç”¨å€¼`6`ï¼Œæˆ‘å¯ä»¥åœ¨æˆ‘çš„
    14â€ MBP ä¸Šå°† 21 ä¸ªåº”ç”¨ç¨‹åºæ”¾å…¥èœå•æ ä¸­ã€‚å¦‚æœæ‚¨çš„åº”ç”¨ç¨‹åºå†æ¬¡è¢«éšè—åœ¨å‡¹æ§½ä¸‹ï¼Œæ‚¨å¯ä»¥é™ä½æ­¤å€¼ã€‚
- en: â€¼ï¸
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: â€¼ï¸
- en: '**NOTE:** Applying this workaround will allow you to fit more items to your
    menu bar but the same issue will resurface if you keep adding more apps which
    run in the menu bar.'
  id: totrans-19
  prefs: []
  type: TYPE_NORMAL
  zh: '**æ³¨æ„ï¼š** åº”ç”¨æ­¤è§£å†³æ–¹æ¡ˆå°†å…è®¸æ‚¨åœ¨èœå•æ ä¸­æ”¾ç½®æ›´å¤šé¡¹ç›®ï¼Œä½†å¦‚æœæ‚¨ç»§ç»­æ·»åŠ åœ¨èœå•æ ä¸­è¿è¡Œçš„æ›´å¤šåº”ç”¨ç¨‹åºï¼Œåˆ™åŒæ ·çš„é—®é¢˜å°†å†æ¬¡å‡ºç°ã€‚'
- en: '[](#c2c7b65789f64fa38e111a3c48b0fa64 "Reverting to the Original Values")Reverting
    to the Original Values'
  id: totrans-20
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
  zh: '[](#c2c7b65789f64fa38e111a3c48b0fa64 "æ¢å¤åˆ°åŸå§‹å€¼")æ¢å¤åˆ°åŸå§‹å€¼'
- en: 'If you''re unhappy with the results, you can delete the settings by executing
    the following commands:'
  id: totrans-21
  prefs: []
  type: TYPE_NORMAL
  zh: å¦‚æœæ‚¨å¯¹ç»“æœä¸æ»¡æ„ï¼Œæ‚¨å¯ä»¥æ‰§è¡Œä»¥ä¸‹å‘½ä»¤åˆ é™¤è®¾ç½®ï¼š
- en: '[PRE1]'
  id: totrans-22
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
- en: '[](#8d04b1e76bdc4b5280fa3d914b4a7efa "Sources")Sources'
  id: totrans-23
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
  zh: '[](#8d04b1e76bdc4b5280fa3d914b4a7efa "æ¥æº")æ¥æº'
- en: 'I first learned about these settings in this answer on the Apple-themed Stack
    Exchange, Ask Different:'
  id: totrans-24
  prefs: []
  type: TYPE_NORMAL
  zh: æˆ‘æ˜¯åœ¨è‹¹æœä¸»é¢˜çš„ Stack Exchangeï¼ŒAsk Different ä¸Šçš„è¿™ä¸ªå›ç­”ä¸­é¦–æ¬¡äº†è§£åˆ°è¿™äº›è®¾ç½®çš„ï¼š
- en: '[](#81f90025480e4081af6df0854230090c "Changelog")Changelog'
  id: totrans-25
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
  zh: '[](#81f90025480e4081af6df0854230090c "æ›´æ–°æ—¥å¿—")æ›´æ–°æ—¥å¿—'
- en: '**12-02-2024 3:17 PM**: I clarified that I have nothing against [Bartender](https://www.macbartender.com)
    after [Eric_WVGG shared a good point in HN](https://news.ycombinator.com/item?id=39343919#39344587).
    I havenâ€™t been writing a lot before and it seems I still have work to do to be
    more considerate towards others ğŸ™‡'
  id: totrans-26
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: '**2024å¹´2æœˆ12æ—¥ ä¸‹åˆ3:17ï¼š** æˆ‘æ¾„æ¸…äº†æˆ‘å¯¹ [Bartender](https://www.macbartender.com) æ²¡æœ‰ä»»ä½•æ„è§ï¼Œè¿™æ˜¯å› ä¸º
    [Eric_WVGG åœ¨ HN åˆ†äº«äº†ä¸€ä¸ªå¾ˆå¥½çš„è§‚ç‚¹](https://news.ycombinator.com/item?id=39343919#39344587)ã€‚æˆ‘ä¹‹å‰æ²¡æœ‰å†™è¿‡å¤ªå¤šä¸œè¥¿ï¼Œä¼¼ä¹æˆ‘ä»ç„¶æœ‰å¾ˆå¤šå·¥ä½œè¦åšï¼Œä»¥å¯¹ä»–äººæ›´åŠ è€ƒè™‘å‘¨åˆ°
    ğŸ™‡'
- en: '**12-02-2024 9:12 PM:** I renamed the article from `Native macOS fix for applications
    hiding under the MacBook Pro notch` to `Built-in MacOS workaround for applications
    hiding under the MacBook Pro notch` to avoid confusion.'
  id: totrans-27
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: '**2024å¹´2æœˆ12æ—¥ ä¸‹åˆ9:12ï¼š** æˆ‘å°†æ–‡ç« ä»`æœ¬æœº macOS ä¿®å¤ MacBook Pro å‡¹æ§½ä¸‹éšè—åº”ç”¨ç¨‹åº`é‡å‘½åä¸º`å†…ç½® MacOS
    è§£å†³æ–¹æ¡ˆï¼Œä»¥è§£å†³ MacBook Pro å‡¹æ§½ä¸‹éšè—åº”ç”¨ç¨‹åºçš„æ··æ·†é—®é¢˜ã€‚'
